Fix security exception auto report
java.lang.SecurityException: Requires ACCESS_MOCK_LOCATION secure setting
at android.os.Parcel.readException(Parcel.java:1322)
at android.os.Parcel.readException(Parcel.java:1276)
at android.location.ILocationManager$Stub$Proxy.setTestProviderLocation(ILocationManager.java:1066)
at android.location.LocationManager.setTestProviderLocation(LocationManager.java:1096)
at com.geeksville.location.TestGPSDriver.sendNewUpdate(TestGPSDriver.java:111)
at com.geeksville.location.TestGPSDriver.access$1(TestGPSDriver.java:95)
at com.geeksville.location.TestGPSDriver$GPSDriverThread.run(TestGPSDriver.java:145)