ver 1.51 - fix localization bug which causes a lot of auto crash reports
java.lang.RuntimeException: Unable to resume activity {com.geeksville.gaggle/com.geeksville.gaggle.TopActivity}: java.lang.IllegalArgumentException: Metros is not a constant in the enum type class com.geeksville.info.Units$Distance
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3128)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3143)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2684)
at android.app.ActivityThread.access$2300(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Metros is not a constant in the enum type class com.geeksville.info.Units$Distance
at java.lang.Enum.valueOf(Enum.java:185)
at com.geeksville.info.Units$Distance.valueOf(Units.java:1)
at com.geeksville.info.Units.setFromPrefs(Units.java:136)
at com.geeksville.gaggle.TopActivity.onResume(TopActivity.java:208)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1149)
at android.app.Activity.performResume(Activity.java:3823)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3118)
... 12 more